server:
  port: 8001
#  servlet-path: /auth
  servlet:
    context-path: /auth
logging:
  level:
    root: info
#spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    jdbc-url: jdbc:mysql://localhost:3306/cas?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: admin
#    hikari:
#      minimum-idle: 5
#      idle-timeout: 600000
#      maximum-pool-size: 10
#      auto-commit: true
#      pool-name: MyHikariCP
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1
