server:
  servlet:
    context-path: /ui
    session:
      cookie:
        name: uisession
  port: 8003

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: DEBUG
